language: java
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - python-pip

install:
  - sudo pip install pyang==1.7.3

script:
  - gradle check --info
  - gradle jacocoRootReport

after_success:
  bash <(curl -s https://codecov.io/bash) -cF server
